"""sprint-04 acceptance — /copilot/query SSE orchestrator."""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Callable
from unittest.mock import MagicMock

import pytest
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[3]


def _parse_sse(raw: str) -> list[dict]:
    """data-only SSE 파서. `event:` 라인은 사용하지 않는다 (revision 2 결정)."""
    events: list[dict] = []
    for block in raw.split("\n\n"):
        if not block.strip():
            continue
        payload = None
        for line in block.splitlines():
            if line.startswith("data:"):
                payload = line[len("data:"):].strip()
        if payload:
            events.append(json.loads(payload))
    return events


@pytest.fixture(autouse=False, scope="function")
def fake_orchestrator_llm(monkeypatch: pytest.MonkeyPatch) -> None:
    """planner + sub-agent + 최종 통합 LLM 호출을 결정론적 fake 로 대체.

    대체 대상: app.agents.llm.call_llm (planner/critique/final 공용 진입).
    반환값은 테스트 호출 경로를 구분해 고정 plan/card 를 돌려준다.
    """
    async def _fake(*, system_prompt_name: str, user_content: str, model: str | None = None, **_: Any) -> str:
        lower = user_content.lower()
        if "plan" in lower and "session_id" in lower:
            return json.dumps({
                "plan_id": "p-fake",
                "session_id": "s-fake",
                "steps": [
                    {"step_id": "a", "agent": "portfolio", "inputs": {},
                     "depends_on": [], "gate_policy": {"schema": True, "domain": True, "critique": True}},
                    {"step_id": "b", "agent": "comparison", "inputs": {},
                     "depends_on": [], "gate_policy": {"schema": True, "domain": True, "critique": True}},
                ],
                "created_at": "2026-04-22T00:00:00Z",
            })
        if "critique" in lower or "final" in lower:
            return json.dumps({"verdict": "pass", "ok": True, "text": "fake critique pass"})
        # step token/result 경로
        return json.dumps({"type": "text", "body": "fake card"})

    monkeypatch.setattr("app.agents.llm.call_llm", _fake, raising=False)


def test_copilot_query_is_sse(fake_orchestrator_llm: None) -> None:
    from app.main import app  # type: ignore

    client = TestClient(app)
    with client.stream("POST", "/copilot/query",
                       json={"query": "AAPL 요약"}) as r:
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("text/event-stream")
        # BLOCKING-2: session_id 자동생성 → 응답 헤더에 포함
        assert "x-copilot-session-id" in {k.lower() for k in r.headers.keys()}
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    # BLOCKING-1: event: 라인이 없어야 한다 (data-only)
    assert "event:" not in body
    events = _parse_sse(body)
    assert events[0]["type"] == "plan.ready"
    assert events[-1]["type"] == "done"
    assert events[-1].get("session_id")  # done payload 에도 session_id


def test_event_order_invariant(fake_orchestrator_llm: None) -> None:
    """plan.ready → (step.start → step.token* → step.gate* → step.result)+ → final.card → done."""
    from app.main import app  # type: ignore

    client = TestClient(app)
    with client.stream("POST", "/copilot/query",
                       json={"query": "내 포트폴리오와 SPY 비교"}) as r:
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    events = _parse_sse(body)
    types = [e["type"] for e in events]
    assert types.count("plan.ready") == 1
    assert types[0] == "plan.ready"
    assert types[-1] == "done"
    assert "final.card" in types
    step_ids = {e["step_id"] for e in events if e.get("step_id")}
    for sid in step_ids:
        if sid == "final":
            continue
        starts = [i for i, e in enumerate(events)
                  if e.get("step_id") == sid and e["type"] == "step.start"]
        results = [i for i, e in enumerate(events)
                   if e.get("step_id") == sid and e["type"] == "step.result"]
        if starts and results:
            assert starts[0] < results[0], f"out-of-order for step {sid}"


def test_final_gate_runs_once_with_reserved_id(fake_orchestrator_llm: None) -> None:
    """BLOCKING-4: 최종 게이트는 step_id == 'final' 로 방출된다."""
    from app.main import app  # type: ignore

    client = TestClient(app)
    with client.stream("POST", "/copilot/query",
                       json={"query": "AAPL 뉴스 요약"}) as r:
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    events = _parse_sse(body)
    final_gate_events = [e for e in events
                         if e["type"] == "step.gate" and e.get("step_id") == "final"]
    gate_names = sorted({e["gate"] for e in final_gate_events})
    assert gate_names == ["critique", "domain", "schema"]


def test_session_id_autogenerated_and_persisted(fake_orchestrator_llm: None) -> None:
    """BLOCKING-2: session_id 미전송 → UUID4 자동생성 → done 직전 SessionTurn 저장."""
    from app.main import app  # type: ignore
    from app.services.session.memory_store import get_session_store  # type: ignore

    # 세션 저장소 초기화 (테스트 격리)
    get_session_store().reset_all()

    client = TestClient(app)
    with client.stream("POST", "/copilot/query",
                       json={"query": "AAPL 요약"}) as r:
        header_sid = r.headers.get("x-copilot-session-id")
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    assert header_sid and len(header_sid) >= 32  # uuid4 hex
    events = _parse_sse(body)
    done = [e for e in events if e["type"] == "done"][-1]
    assert done["session_id"] == header_sid
    # done 직전 SessionTurn 이 저장되어 있어야 한다
    store = get_session_store()
    turns = store.list_turns(header_sid)
    assert len(turns) == 1
    assert turns[0].final_card is not None


def test_one_step_failure_does_not_break_stream(
    fake_orchestrator_llm: None, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """BLOCKING-6 + AC-04-4: gate fail 시 degraded 플래그 포함 step.result 도 방출."""
    monkeypatch.setenv("COPILOT_FORCE_FAIL_STEP", "b")
    from app.main import app  # type: ignore

    client = TestClient(app)
    with client.stream("POST", "/copilot/query",
                       json={"query": "AAPL 뉴스 + 비교"}) as r:
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    events = _parse_sse(body)
    types = [e["type"] for e in events]
    assert "error" in types
    assert types[-1] == "done"
    degraded_results = [e for e in events
                        if e["type"] == "step.result"
                        and e.get("card", {}).get("degraded") is True]
    assert len(degraded_results) >= 1


def test_independent_steps_run_in_parallel(fake_orchestrator_llm: None) -> None:
    """BLOCKING-3: _harness_step_delay_ms 를 오케스트레이터가 asyncio.sleep 으로 변환."""
    from app.main import app  # type: ignore

    client = TestClient(app)
    t0 = time.perf_counter()
    with client.stream("POST", "/copilot/query",
                       json={"query": "AAPL vs MSFT 비교 + 뉴스",
                             "_harness_step_delay_ms": 400}) as r:
        body = "".join(chunk.decode() for chunk in r.iter_bytes())
    elapsed = time.perf_counter() - t0
    events = _parse_sse(body)
    step_count = len({e.get("step_id") for e in events if e.get("step_id")} - {"final"})
    assert step_count >= 2
    assert elapsed < step_count * 0.4 * 0.7, (
        f"looks sequential: {elapsed:.2f}s for {step_count} steps"
    )


def test_direct_import_no_self_http(fake_orchestrator_llm: None) -> None:
    """BLOCKING-5: 오케스트레이터가 /copilot/plan 을 HTTP 자기호출하지 않는다.

    `httpx.AsyncClient.post` 를 스파이로 감싸 /copilot/plan 으로의 호출이 0회임을 검증.
    """
    import httpx

    original_post = httpx.AsyncClient.post
    calls: list[str] = []

    async def _spy(self, url: str, *args: Any, **kwargs: Any):  # type: ignore[no-untyped-def]
        calls.append(str(url))
        return await original_post(self, url, *args, **kwargs)

    with pytest.MonkeyPatch.context() as mp:
        mp.setattr(httpx.AsyncClient, "post", _spy)
        from app.main import app  # type: ignore

        client = TestClient(app)
        with client.stream("POST", "/copilot/query",
                           json={"query": "AAPL 요약"}) as r:
            for _ in r.iter_bytes():
                pass
    assert not any("/copilot/plan" in c for c in calls), (
        f"orchestrator self-called /copilot/plan via HTTP: {calls}"
    )
