/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Symbols
         * @description 지원 심볼 목록 (데모 고정 샘플)
         */
        get: operations["list_symbols_market_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Symbols
         * @description 심볼 통합 검색 (upbit + yahoo + naver_kr + alias).
         *
         *     - 4개 소스를 asyncio.gather 로 병렬 호출
         *     - (market, symbol) 기준 dedupe, 높은 score 유지
         *     - score 내림차순 정렬 후 상위 50개 반환
         *     - score 필드는 응답에 포함되지 않음 (SymbolInfo.score 는 exclude=True)
         */
        get: operations["search_symbols_market_symbols_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/quotes/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quote
         * @description 단일 심볼 시세 조회 (stub — legacy 호환)
         */
        get: operations["get_quote_market_quotes__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/quotes/{market}/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Quote
         * @description market별 단일 심볼 현재가 조회. Redis 캐시(TTL 5s) 적용.
         */
        get: operations["get_market_quote_market_quotes__market___code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/ohlc/{market}/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ohlc
         * @description OHLC 캔들 조회. Redis 캐시(TTL 60s) 적용.
         */
        get: operations["get_ohlc_market_ohlc__market___code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist
         * @description 워치리스트 조회 (user_id='demo' 고정).
         */
        get: operations["list_watchlist_market_watchlist_items_get"];
        put?: never;
        /**
         * Add Watchlist
         * @description 워치리스트에 심볼 추가.
         */
        post: operations["add_watchlist_market_watchlist_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/watchlist/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Watchlist
         * @description 워치리스트 항목 삭제.
         */
        delete: operations["delete_watchlist_market_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description 임의 투자 데이터를 받아 Router → Analyzer → 3단 게이트 파이프라인을 실행한다.
         *
         *     - `data` 만 주어진 경우: 그대로 분석
         *     - `symbol` 이 주어진 경우: market 어댑터로 OHLC 프리패치 후 주입
         *     - `context.ohlc` 가 주어진 경우: 그대로 rows 로 변환해 주입
         *     - `include_portfolio_context=True` 인 경우: DB에서 holdings를 조회해 AgentState에 주입
         */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Csv
         * @description CSV 파일 업로드 → 자동 분석.
         *
         *     - content-type: text/csv 또는 application/vnd.ms-excel
         *     - 파일 크기: ≤ 10MB (초과 시 413)
         *     - 인코딩: utf-8 / cp949 자동 탐지
         *     - 행 수 > 300 이면 모델을 opus 로 자동 승급
         *     - 결과는 파일 해시 + user_note 기반 캐시 키로 5분 캐싱
         */
        post: operations["analyze_csv_analyze_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Holdings
         * @description 보유 종목 전체 조회.
         */
        get: operations["list_holdings_portfolio_holdings_get"];
        put?: never;
        /**
         * Create Holding
         * @description 보유 종목 추가.
         */
        post: operations["create_holding_portfolio_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Holding
         * @description 보유 종목 삭제.
         */
        delete: operations["delete_holding_portfolio_holdings__holding_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Holding
         * @description 수량/평단가 수정.
         */
        patch: operations["update_holding_portfolio_holdings__holding_id__patch"];
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description 포트폴리오 집계 요약 (현재가 기반 실시간 계산).
         */
        get: operations["get_summary_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description 포트폴리오 스냅샷 조회 (날짜 범위 필터).
         */
        get: operations["list_snapshots_portfolio_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebalance
         * @description 리밸런싱 제안 생성.
         *
         *     결정적 계산(순수함수)으로 actions 배열을 생성하고,
         *     LLM 해석(RebalanceAnalyzer)을 옵션으로 추가.
         *     LLM 실패 시 llm_analysis=None, status="degraded" 로 graceful degrade.
         */
        post: operations["rebalance_portfolio_rebalance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeContext
         * @description 선택적 부가 컨텍스트. 현재는 OHLC 프리패치 결과만.
         */
        AnalyzeContext: {
            /**
             * Ohlc
             * @description 서버 또는 클라이언트가 제공한 OHLC 시계열
             */
            ohlc?: components["schemas"]["OhlcBar"][] | null;
        };
        /** AnalyzeMeta */
        AnalyzeMeta: {
            /**
             * Asset Class
             * @description Router 가 결정한 자산군
             */
            asset_class: string;
            /**
             * Router Reason
             * @description Router 가 선택한 이유 (한 문장)
             */
            router_reason: string;
            /**
             * Gates
             * @description 각 게이트의 최종 상태
             */
            gates: {
                [key: string]: string;
            };
            /**
             * Latency Ms
             * @description 그래프 실행 소요 시간(ms)
             */
            latency_ms?: number | null;
            /**
             * Analyzer Name
             * @description 어떤 analyzer 가 실행되었는지 (stock | crypto | fx | ...)
             */
            analyzer_name?: string | null;
            /**
             * Evidence Snippets
             * @description critique 통과 후 확정된 근거 인용 3~5개
             */
            evidence_snippets?: string[];
            /** @description 직전 요청의 프롬프트 캐시/토큰 사용량 */
            cache?: components["schemas"]["CacheMetrics"] | null;
        };
        /**
         * AnalyzeRequest
         * @description 임의 투자 데이터를 받아 자동 분석을 요청한다.
         */
        AnalyzeRequest: {
            /**
             * Data
             * @description 분석할 원시 데이터 rows. symbol 만으로도 분석할 경우 빈 리스트 허용.
             */
            data?: {
                [key: string]: unknown;
            }[];
            /**
             * Query
             * @description 자연어 분석 지시 (선택)
             */
            query?: string | null;
            /**
             * Asset Class Hint
             * @description Router 힌트: stock | crypto | fx | macro | auto
             */
            asset_class_hint?: string | null;
            /** @description 심볼 분석 요청. 존재 시 서버가 market 어댑터로 OHLC 를 프리패치한다. */
            symbol?: components["schemas"]["SymbolRef"] | null;
            /** @description 클라이언트가 선계산해 넘기는 OHLC 등 부가 컨텍스트 */
            context?: components["schemas"]["AnalyzeContext"] | null;
            /**
             * Include Portfolio Context
             * @description True면 서버가 DB에서 holdings를 조회해 AgentState에 주입. LLM이 개인화된 분석 수행.
             * @default false
             */
            include_portfolio_context: boolean;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Request Id
             * @description 추적용 UUID
             */
            request_id: string;
            /**
             * Status
             * @description ok | error | degraded
             */
            status: string;
            /**
             * Result
             * @description Analyzer 출력 (자산군별 상이)
             */
            result?: {
                [key: string]: unknown;
            } | null;
            meta: components["schemas"]["AnalyzeMeta"];
        };
        /** Body_analyze_csv_analyze_csv_post */
        Body_analyze_csv_analyze_csv_post: {
            /** File */
            file: string;
            /**
             * User Note
             * @default
             */
            user_note: string;
            /**
             * Symbol Hint
             * @default
             */
            symbol_hint: string;
            /**
             * Include Portfolio Context
             * @default false
             */
            include_portfolio_context: boolean;
        };
        /** CacheMetrics */
        CacheMetrics: {
            /**
             * Read Tokens
             * @description 프롬프트 캐시 히트 토큰
             * @default 0
             */
            read_tokens: number;
            /**
             * Creation Tokens
             * @description 캐시 생성(기록) 토큰
             * @default 0
             */
            creation_tokens: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            services: components["schemas"]["ServiceStatus"];
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /** HoldingCreate */
        HoldingCreate: {
            /**
             * Market
             * @description upbit | binance | yahoo | naver_kr
             */
            market: string;
            /**
             * Code
             * @description 심볼/코드 (예: KRW-BTC, AAPL)
             */
            code: string;
            /**
             * Quantity
             * @description 보유 수량
             */
            quantity: number | string;
            /**
             * Avg Cost
             * @description 평균 매입 단가
             */
            avg_cost: number | string;
            /**
             * Currency
             * @description 통화 코드 (KRW/USD/USDT/EUR/JPY)
             */
            currency: string;
        };
        /**
         * HoldingDetail
         * @description 집계 결과에서 종목별 상세.
         */
        HoldingDetail: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Code */
            code: string;
            /** Quantity */
            quantity: string;
            /** Avg Cost */
            avg_cost: string;
            /** Currency */
            currency: string;
            /** Current Price */
            current_price: string;
            /** Current Price Krw */
            current_price_krw: string;
            /** Value Krw */
            value_krw: string;
            /** Cost Krw */
            cost_krw: string;
            /** Pnl Krw */
            pnl_krw: string;
            /** Pnl Pct */
            pnl_pct: string;
        };
        /** HoldingResponse */
        HoldingResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Market */
            market: string;
            /** Code */
            code: string;
            /** Quantity */
            quantity: string;
            /** Avg Cost */
            avg_cost: string;
            /** Currency */
            currency: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** HoldingUpdate */
        HoldingUpdate: {
            /** Quantity */
            quantity?: number | string | null;
            /** Avg Cost */
            avg_cost?: number | string | null;
        };
        /** LLMAnalysis */
        LLMAnalysis: {
            /** Headline */
            headline: string;
            /** Narrative */
            narrative: string;
            /** Warnings */
            warnings?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /**
         * OhlcBar
         * @description OHLC 캔들 하나
         */
        OhlcBar: {
            /**
             * Ts
             * @description ISO-8601 UTC
             */
            ts: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume?: number | null;
        };
        /**
         * PortfolioSummary
         * @description GET /portfolio/summary 응답.
         */
        PortfolioSummary: {
            /**
             * User Id
             * @default demo
             */
            user_id: string;
            /** Total Value Krw */
            total_value_krw: string;
            /** Total Cost Krw */
            total_cost_krw: string;
            /** Total Pnl Krw */
            total_pnl_krw: string;
            /** Total Pnl Pct */
            total_pnl_pct: string;
            /** Daily Change Krw */
            daily_change_krw: string;
            /** Daily Change Pct */
            daily_change_pct: string;
            /**
             * Asset Class Breakdown
             * @description {'crypto': '0.50', 'stock_us': '0.30', ...}
             */
            asset_class_breakdown: {
                [key: string]: string;
            };
            /** Holdings */
            holdings: components["schemas"]["HoldingDetail"][];
        };
        /** Quote */
        Quote: {
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @description upbit | binance | yahoo | naver_kr
             * @default unknown
             */
            market: string;
            /** Price */
            price: number;
            /**
             * Change
             * @description 전일 대비 변화량
             * @default 0
             */
            change: number;
            /**
             * Change Pct
             * @description 전일 대비 변화율(%)
             * @default 0
             */
            change_pct: number;
            /** Volume */
            volume?: number | null;
            /**
             * Currency
             * @description KRW | USD | USDT 등
             * @default USD
             */
            currency: string;
            /**
             * Timestamp
             * @description ISO-8601 UTC
             */
            timestamp: string;
        };
        /** RebalanceAction */
        RebalanceAction: {
            /**
             * Action
             * @enum {string}
             */
            action: "buy" | "sell";
            /** Market */
            market: string;
            /** Code */
            code: string;
            /** Asset Class */
            asset_class: string;
            /** Quantity */
            quantity: string;
            /** Estimated Value Krw */
            estimated_value_krw?: string | null;
            /** Reason */
            reason: string;
        };
        /** RebalanceConstraints */
        RebalanceConstraints: {
            /**
             * Max Single Weight
             * @description 단일 종목 최대 비중
             * @default 0.5
             */
            max_single_weight: number;
            /**
             * Min Trade Krw
             * @description 최소 거래액(KRW)
             * @default 100000
             */
            min_trade_krw: number | string;
            /**
             * Allow Fractional
             * @description 소수점 수량 허용 (주식은 기본 False 권장)
             * @default true
             */
            allow_fractional: boolean;
        };
        /** RebalanceMeta */
        RebalanceMeta: {
            /** Latency Ms */
            latency_ms?: number | null;
            /** Gates */
            gates: {
                [key: string]: string;
            };
            /** Evidence Snippets */
            evidence_snippets?: string[];
        };
        /** RebalanceRequest */
        RebalanceRequest: {
            target_allocation: components["schemas"]["TargetAllocation"];
            constraints?: components["schemas"]["RebalanceConstraints"];
        };
        /** RebalanceResponse */
        RebalanceResponse: {
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /** Current Allocation */
            current_allocation: {
                [key: string]: number;
            };
            /** Target Allocation */
            target_allocation: {
                [key: string]: number;
            };
            /** Drift */
            drift: {
                [key: string]: number;
            };
            /** Actions */
            actions: components["schemas"]["RebalanceAction"][];
            /** Expected Allocation */
            expected_allocation: {
                [key: string]: number;
            };
            summary: components["schemas"]["RebalanceSummary"];
            llm_analysis?: components["schemas"]["LLMAnalysis"] | null;
            meta: components["schemas"]["RebalanceMeta"];
        };
        /** RebalanceSummary */
        RebalanceSummary: {
            /** Total Trades */
            total_trades: number;
            /** Total Sell Value Krw */
            total_sell_value_krw: string;
            /** Total Buy Value Krw */
            total_buy_value_krw: string;
            /** Rebalance Cost Estimate Krw */
            rebalance_cost_estimate_krw: string;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /** Db */
            db: string;
            /** Redis */
            redis: string;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Snapshot Date */
            snapshot_date: string;
            /** Total Value Krw */
            total_value_krw: string;
            /** Total Pnl Krw */
            total_pnl_krw: string;
            /** Asset Class Breakdown */
            asset_class_breakdown: {
                [key: string]: unknown;
            };
            /** Holdings Detail */
            holdings_detail: unknown[];
            /** Created At */
            created_at: string;
        };
        /** Symbol */
        Symbol: {
            /**
             * Symbol
             * @description 티커 심볼 (예: AAPL, KRW-BTC)
             */
            symbol: string;
            /**
             * Name
             * @description 자산 이름
             */
            name: string;
            /**
             * Asset Class
             * @description stock | crypto | fx | macro
             */
            asset_class: string;
            /**
             * Exchange
             * @description 거래소 코드
             */
            exchange?: string | null;
            /**
             * Market
             * @description upbit | binance | yahoo | naver_kr
             */
            market?: string | null;
        };
        /**
         * SymbolInfo
         * @description 심볼 검색 결과
         */
        SymbolInfo: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Exchange */
            exchange?: string | null;
            /** Market */
            market: string;
            /** Currency */
            currency?: string | null;
        };
        /**
         * SymbolRef
         * @description 업로드 없이 심볼만으로 분석할 때 사용하는 참조.
         */
        SymbolRef: {
            /**
             * Market
             * @description upbit | binance | yahoo | naver_kr
             */
            market: string;
            /**
             * Code
             * @description 티커/코드. 예: KRW-BTC, AAPL
             */
            code: string;
        };
        /**
         * TargetAllocation
         * @description 자산군별 목표 비중. 합계 1.0 (±0.001 허용).
         */
        TargetAllocation: {
            /**
             * Stock Kr
             * @default 0
             */
            stock_kr: number;
            /**
             * Stock Us
             * @default 0
             */
            stock_us: number;
            /**
             * Crypto
             * @default 0
             */
            crypto: number;
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Fx
             * @default 0
             */
            fx: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /**
             * Market
             * @description upbit | binance | yahoo | naver_kr
             */
            market: string;
            /**
             * Code
             * @description 심볼/코드 (예: KRW-BTC, AAPL)
             */
            code: string;
            /** Memo */
            memo?: string | null;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /** Id */
            id: number;
            /** Market */
            market: string;
            /** Code */
            code: string;
            /** Memo */
            memo?: string | null;
            /**
             * Created At
             * @description ISO-8601 UTC
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_symbols_market_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Symbol"][];
                };
            };
        };
    };
    search_symbols_market_symbols_search_get: {
        parameters: {
            query: {
                /** @description 검색 키워드 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_market_quotes__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_quote_market_quotes__market___code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlc_market_ohlc__market___code__get: {
        parameters: {
            query?: {
                interval?: string;
                limit?: number;
            };
            header?: never;
            path: {
                market: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcBar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_market_watchlist_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"][];
                };
            };
        };
    };
    add_watchlist_market_watchlist_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_market_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_csv_analyze_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_csv_analyze_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_portfolio_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingResponse"][];
                };
            };
        };
    };
    create_holding_portfolio_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_portfolio_holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_holding_portfolio_holdings__holding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    list_snapshots_portfolio_snapshots_get: {
        parameters: {
            query?: {
                /** @description 시작 날짜 (YYYY-MM-DD) */
                from?: string | null;
                /** @description 종료 날짜 (YYYY-MM-DD) */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebalance_portfolio_rebalance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebalanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebalanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
